
Feature: US03: guardaespaldas disponibles

Como usuario del aplicativo quiero  poder observar en forma de galería 
a los guardaespaldas que están disponibles o en servicio para de esta manera contratarlo
#-------------------------------------------------------------
Scenario : E01 - Observar a los guardaespaldas

Given que el usuario desea ver en forma generala los guardaespaldas que trabajan mediante nuestra aplicación

When se encuentre en la pantalla principal

Then podrá acceder al apartado de guardaespaldas que le mostraran a cada uno de ellos en forma de galería.