Feature: US04: Perfil de los guardaespaldas

Como usuario del aplicativo quiero poder observar en forma de galería
a los guardaespaldas que están disponibles para solicitar un servicio

#-------------------------------------------------------------
Scenario : E01 - Observar el perfil de un guardaespaldas especifico

Given que el usuario desea ver el perfil de un guardaespaldas en especifico

When se encuentre en el apartado de guardaespaldas

Then podrá seleccionar a uno en específico para poder ver sus datos y estado de servicio.