
Feature: US05: Solicitar el servicio

Como usuario del aplicativo quierpo poder solicitar el servicio de guardaespaldas
a través de un carrito virtual para satisfacer mi necesidad.


#-------------------------------------------------------------
Scenario : E01 - Reservar  el servicio

Given que el usuario desea poder solicitar el servicio de guardaespaldas

When se encuentre en el perfil de un guardaespaldas

Then podrá seleccionar la opción de solicitar servicio si el guardaespaldas está disponible para guardarlo dentro de un carrito virtual.



