Feature: US7:Configuracion de datos 


Como usuario del aplicativo deseo poder configurar mis datos en un apartado de la aplicación
para actualizar mis datos.

#-------------------------------------------------------------
Scenario : E01 - Datos personales

Given que el usuario desea poder configurar ciertos datos de su perfil

When Cuando se encuentre en la pantalla principal

Then podrá seleccionar el menú y la opción de configuración donde podrá actualizar todos sus datos

