Feature: US10:Cancelacion del Servicio


Como usuario del aplicativo deseo que antes de que el servicio se lleve a cabo tenga una opción de cancelar el servicio
para poder cambiar mi decision

Scenario : Anulacion del servicio


Given que el usuario desea poder cancelar el servicio antes que se lleve a cabo

When se encuentre dentro del carrito de reservas y solicitudes

Then podrá seleccionar la opción de cancelar el servicio y podrá confirmarlo a través de una nueva pantalla.
